export const archetypeEdgeMap: Record<string, string> = {
  '导师':   'zh-CN-YunjianNeural',
  '盟友':   'zh-CN-YunxiNeural',
  '反派':   'zh-CN-YunyangNeural',
  '神秘人': 'zh-CN-YunjianNeural',
  '商人':   'zh-CN-YunyangNeural',
  '守卫':   'zh-CN-YunxiaNeural',
  '平民':   'zh-CN-XiaoyiNeural',
  '智者':   'zh-CN-YunjianNeural',
  '冷酷':   'zh-CN-XiaoxiaoNeural',
  '温柔':   'zh-CN-XiaoxiaoNeural',
  '活泼':   'zh-CN-XiaoyiNeural',
  '邪恶':   'zh-CN-YunyangNeural',
  '儿童':   'zh-CN-XiaoyiNeural',
}

export const archetypeKokoroMap: Record<string, string> = {
  '导师':   'zm_yunyang',
  '盟友':   'zm_yunxi',
  '反派':   'zm_yunyang',
  '神秘人': 'zm_yunjian',
  '商人':   'zm_yunyang',
  '守卫':   'zm_yunxia',
  '平民':   'zf_xiaobei',
  '智者':   'zm_yunjian',
  '冷酷':   'zf_xiaoxiao',
  '温柔':   'zf_xiaobei',
  '活泼':   'zf_xiaoni',
  '邪恶':   'zm_yunyang',
  '儿童':   'zf_xiaoyi',
  '长老':   'zm_yunjian',
  '武将':   'zm_yunxia',
  '贵族':   'zf_xiaoxiao',
}
